api_platform:
    title: 'API historique sociétés'
    description: 'Consulter les modifications sur les sociétés '
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
